# Generated by Django 5.2.16 on 2026-07-26 14:15

from django.db import migrations, models

import chat.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("openid_connect", "OpenID Connect (e.g. LinkedIn)"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        help_text='OpenID Connect only, e.g. "linkedin". Blank for Google/GitHub.',
                        max_length=40,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Display name, e.g. "LinkedIn".',
                        max_length=100,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="The OAuth app's client id (public).", max_length=255
                    ),
                ),
                (
                    "secret",
                    chat.fields.EncryptedTextField(
                        help_text="Client secret. Stored encrypted; only the last 4 chars show."
                    ),
                ),
                (
                    "server_url",
                    models.CharField(
                        blank=True,
                        help_text="OpenID Connect issuer, e.g. https://www.linkedin.com/oauth.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to disable without deleting."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "social login app",
                "verbose_name_plural": "social login apps",
                "ordering": ["provider", "provider_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_id"), name="unique_oauth_provider"
                    )
                ],
            },
        ),
    ]
