# Generated by Django 5.2.16 on 2026-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthcredential",
            name="link_by_verified_email",
            field=models.BooleanField(
                default=False,
                help_text="Sign the visitor into an existing account when this provider "
                "reports their email as verified. Only tick it for providers that really "
                "verify — otherwise this is a way into any account. Off means they are "
                "told the account already exists instead.",
                verbose_name="link by verified email",
            ),
        ),
    ]
