# Generated by Django 5.1.15 on 2026-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text='Stable id, e.g. "cv" or "bio".', unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Group label, e.g. "Compensation", "Availability", "Personal".',
                        max_length=50,
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="e.g. Salary expectations", max_length=200),
                ),
                ("answer", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide without deleting."
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Lower numbers show first."),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "category", "question"],
            },
        ),
    ]
