# Generated by Django 5.1.15 on 2026-07-13 17:47

from django.db import migrations, models

import chat.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_document_fact"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text='LiteLLM provider prefix, e.g. "groq" or "gemini".',
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional note, e.g. which account the key is from.",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    chat.fields.EncryptedTextField(
                        help_text="Stored encrypted; only the last 4 chars show."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to disable without deleting."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "id"],
            },
        ),
    ]
