# Generated by Django 5.1.15 on 2026-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_llmcredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(db_index=True, max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
