# Generated by Django 5.1.15 on 2026-07-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_requestlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmcredential",
            options={
                "ordering": ["provider", "id"],
                "verbose_name": "API credential",
                "verbose_name_plural": "API credentials",
            },
        ),
        migrations.AlterField(
            model_name="llmcredential",
            name="provider",
            field=models.CharField(
                help_text='Provider / integration name, e.g. "mistral", "groq", or "github".',
                max_length=50,
            ),
        ),
    ]
