# Generated by Django 5.1.15 on 2026-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_llmcredential_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="context_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
