# Generated by Django 5.2.16 on 2026-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_conversation_context_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text='LiteLLM model id, e.g. "mistral/mistral-small-latest".',
                        max_length=100,
                    ),
                ),
                (
                    "period",
                    models.DateField(help_text="First day of the calendar month this row totals."),
                ),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period", "model"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "period"),
                        name="unique_token_usage_model_period",
                    )
                ],
            },
        ),
    ]
