# Generated by Django 5.2.16 on 2026-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_tokenusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_content_type",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="document",
            name="file_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="file_uploaded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(
                help_text="What the assistant reads. Filled from an uploaded file's "
                "extracted text — editable afterwards, e.g. to fix a rough PDF extraction."
            ),
        ),
    ]
