# Generated by Django 5.2.16 on 2026-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_document_file_content_type_document_file_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="LiteLLM model id, including its provider prefix — e.g. "
                        '"mistral/mistral-small-latest" or "zai/glm-4.7-flash". The prefix '
                        "selects which API credential is used.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Drag the rows to reorder, then press Save. Lowest runs first.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to take a model out of the chain without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "chat model",
                "verbose_name_plural": "chat models",
                "ordering": ["order", "id"],
            },
        ),
    ]
