# Generated by Django 5.2.16 on 2026-07-17 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_seed_chat_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fact",
            options={"ordering": ["category", "question"]},
        ),
        migrations.RemoveField(
            model_name="fact",
            name="order",
        ),
    ]
