# Generated by Django 5.2.16 on 2026-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_alter_fact_options_remove_fact_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(-1, "Thumbs down"), (1, "Thumbs up")],
                help_text="Visitor feedback: +1 up, -1 down, blank if unrated.",
                null=True,
            ),
        ),
    ]
